embedded.zookeeper.port: 2181

# DemoService version
oms.service.version: 1.0.0

dubbo:
    protocol:
        # Dubbo Protocol
        name: dubbo
        # Random port
        port: -1

    # Dubbo Registry
#    registry.address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
#    registry.file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

    # Base packages to scan Dubbo Component: @org.apache.dubbo.config.annotation.Service
#    scan.base-packages: com.lfx.tcc.provider

# Spring boot application
spring:
    application.name: oms-provider


